### ISSUE TITLE
About method "mulut_predict"

### ISSUE THREAD

**Issue by wzl281158150** [ddlee-cn/MuLUT#3]
Hello, thanks for your work. The project is nicely organized and the code is easily readable.
However, i'm confused about the code in method "**mulut_predict**" in "**1_train_model.py**"

```python
if s + 1 == stages:
    avg_factor, bias, norm = len(modes), 0, 1
    x = round_func((pred / avg_factor) + bias)
    if phase == "train":
        x = x / 255.0
else:
    avg_factor, bias, norm = len(modes) * 4, 127, 255.0
    x = round_func(torch.clamp((pred / avg_factor) + bias, 0, 255)) / norm
```
I know that "pred" is the sum of all modes ("sdy" for example) with 4 direction (0, 90, 180, 270).
But, why does "avg_factor" equal 3 (len(modes) == 3) instead of 12 (3 modes * 4 direction == 12) in the final stage?

**Comment by ddlee-cn** [comment]
Thanks for your interest.

This is an empirical find, that averaging over four rotational predictions results in performance drop. Thus, we follow SR-LUT (line [here](https://github.com/yhjo09/SR-LUT/blob/a18dafe4c3b1f796e14436468922590b97458108/1_Train_deep_model/Train_Model_S.py#L254)).

Nevertheless, I have a theory that averaging over four rotational predictions reduce the dynamic range of each prediction (from 127 to 127/4). Hope it helps.

**Comment by wzl281158150** [comment]
Thanks for your explanation! It helps a lot.
