### ISSUE TITLE
About Image Demosaicking

### ISSUE THREAD

**Issue by darkbridge** [ddlee-cn/MuLUT#4]
hi, In the source code, DMNet is used to convert input like 1*1*4*4 RGGB to 1*3*4*4 RGB, but when I test, it seem not like this, the output is still 1* 1* 4*4，is there something wrong with my understanding

**Comment by ddlee-cn** [comment]
Sorry for the inconvenience, the current code is not ready for other tasks. To construct a demosaicing network, the `out_c` parameter should be multiplied in the configuration `out_channel` of the laster conv layer before pixelshuffle (this [line](https://github.com/ddlee-cn/MuLUT/blob/de23a517d21c2f07fd6abf0f4663f1e7007a9528/common/network.py#L86) in MuLUTUnit).
