### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by WangXuCh** [ddlee-cn/MuLUT#5]
Can't get attribute 'SRUnit' on <module 'common.network' from '..\\common\\network.py'>

**Comment by WangXuCh** [comment]
I just used the model (Model_200000.pth) which you provided in the first part for the operation of the second part.

**Comment by ddlee-cn** [comment]
Sorry for the bug. Please replace "SRUnit" with "MuLUTUnit" in keys of the model.stated_dict().

**Comment by Cruise97Liang** [comment]
> Can't get attribute 'SRUnit' on <module 'common.network' from '..\common\network.py'>



> I just used the model (Model_200000.pth) which you provided in the first part for the operation of the second part.
Excuse me, did "Model_200000.pth" appear in your python command? If yes, could you tell me where it was specifically? Thank you!

**Comment by ddlee-cn** [comment]
> 

It is used as the model loading path [here](https://github.com/ddlee-cn/MuLUT/blob/6ba63e6365faeda06d8824c066e4e80e1b1d63d0/sr/2_transfer_to_lut.py#L82).

**Comment by WangXuCh** [comment]
> > 
> 
> It is used as the model loading path [here](https://github.com/ddlee-cn/MuLUT/blob/6ba63e6365faeda06d8824c066e4e80e1b1d63d0/sr/2_transfer_to_lut.py#L82).

Thank you!

**Comment by Note-Liu** [comment]
> Please replace "SRUnit" with "MuLUTUnit" in keys of the model.stated_dict().

May I ask how you resolved it？

**Comment by ddlee-cn** [comment]
> > Please replace "SRUnit" with "MuLUTUnit" in keys of the model.stated_dict().
> 
> May I ask how you resolved it？

Please refer to this one: https://discuss.pytorch.org/t/dataparallel-changes-parameter-names-issue-with-load-state-dict/60211/2

Otherwise, you can retrain the model with step 1 code.
