### ISSUE TITLE
energy cost 

### ISSUE THREAD

**Issue by zhjy2016** [ddlee-cn/MuLUT#8]
Can you provide that how to measure the energy cost for the paper? thank you.

**Comment by ddlee-cn** [comment]
> Can you provide that how to measure the energy cost for the paper? thank you.

Please send me an email and I will reply with the excel file we used to estimate energy cost.

**Comment by zhjy2016** [comment]
thanks， my email ***@***.***&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月30日(星期一) 中午12:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ddlee-cn/MuLUT] energy cost  (Issue #8)





  
Can you provide that how to measure the energy cost for the paper? thank you.
  
Please send me an email and I will reply with the excel file we used to estimate energy cost.

**Comment by ddlee-cn** [comment]
Github hides email address in comments. Anyway, I found the email address in your SPLUT paper. The excel file is sent. Hope it is helpful.

**Comment by zhjy2016** [comment]
Thanks a lot!
